feat: added faq section
dscnitrourkela/project-unagi pull request #20
Opened 2024-03-13 17:50 UTC by praptippradhan

2024-03-14 17:20 UTC, praptippradhan commented
@starkjay21 and @Shurtu-gal please review.

2024-03-14 18:00 UTC, ashutosh-rath02 requested changes
Hey there @praptippradhan , your component looks good. I have suggested a few changes. Please complete it. Try using tailwind classes in the whole file. I have marked some out for you.

2024-03-17 12:07 UTC, Mixel2004 commented on package.json
> -		"tailwind-merge": "^2.2.1",
it is being used in src\lib\utils.js

2024-03-17 12:26 UTC, ashutosh-rath02 approved these changes

2024-03-17 12:27 UTC, merged